apiVersion: v2
name: talay-worker
description: Background worker chart for Java, Node and generic workloads
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: talay-common
    version: 0.1.0
    repository: file://../talay-common
