{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "talay.externalSecretName" . }}
  labels:
    {{- include "talay.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName | quote }}
    kind: {{ .Values.externalSecret.secretStoreKind | quote }}
  target:
    name: {{ include "talay.externalSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ required "externalSecret.remoteKey is required" .Values.externalSecret.remoteKey | quote }}
{{- end }}
