{{- if .Values.registrySecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.registrySecret.targetName | quote }}
  labels:
    {{- include "talay.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.registrySecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.registrySecret.secretStoreName | quote }}
    kind: {{ .Values.registrySecret.secretStoreKind | quote }}
  target:
    name: {{ .Values.registrySecret.targetName | quote }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
        key: {{ required "registrySecret.remoteKey is required" .Values.registrySecret.remoteKey | quote }}
{{- end }}
