name: verify-charts

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  helm:
    uses: cantalay/talay-workflows/.github/workflows/helm.yaml@65a99720b5461e49a8113d647651cf743f961abb
    with:
      charts-directory: charts
      helm-version: v4.2.4
      publish: false
      registry-namespace: cantalay/charts
