name: verify-charts

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  helm:
    uses: cantalay/talay-workflows/.github/workflows/helm.yaml@107e3e43dee30ea1b4874c7bc150f90769b55efc
    with:
      charts-directory: charts
      helm-version: v4.2.4
      publish: false
      registry-namespace: cantalay/charts
